server:
  port: 9090

spring:
  datasource:
    url: jdbc:sqlserver://java-demo-sql-server.database.windows.net:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME:javaadmin}
    password: ${DB_PASSWORD:M!rf@lah123}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
