server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=testdb;encrypt=true;trustServerCertificate=true;loginTimeout=30}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourPassword@1234}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: accordinnovations-backend
logging:
  file:
    name: logs/backend-app.log
  level:
    root: INFO
    com.accordinnovations: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info
